# Generated by Django 5.1.1 on 2024-09-16 16:32

import cloudinary.models
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Author image')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='País')),
            ],
        ),
    ]
