# Generated by Django 4.0.3 on 2022-03-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_excerpt_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(max_length=500),
        ),
    ]
